### ISSUE TITLE
Unable to npm run dev this due to a certificate issue

### ISSUE THREAD

**Issue by lyndonb1** [ofekashery/react-dashboard-design#24]
npm install

up to date, audited 339 packages in 4s

52 packages are looking for funding
  run `npm fund` for details

10 vulnerabilities (1 moderate, 4 high, 5 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
PS C:\Users\lyndo\src\react-dashboard-design\react-dashboard-design> npm run dev

> react-dashboard-design@0.2.0 dev
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
warn  - Minimum recommended TypeScript version is v4.3.2, older versions can potentially be incompatible with Next.js. Detected: 4.2.4
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:68:19)
    at Object.createHash (node:crypto:138:10)
    at BulkUpdateDecorator.hashFactory (C:\Users\lyndo\src\react-dashboard-design\react-dashboard-design\node_modules\next\dist\compiled\webpack\bundle5.js:138971:18)
    at BulkUpdateDecorator.update (C:\Users\lyndo\src\react-dashboard-design\react-dashboard-design\node_modules\next\dist\compiled\webpack\bundle5.js:138872:50)
    at OriginalSource.updateHash (C:\Users\lyndo\src\react-dashboard-design\react-dashboard-design\node_modules\next\dist\compiled\webpack-sources3\index.js:1:10264)
    at NormalModule._initBuildHash (C:\Users\lyndo\src\react-dashboard-design\react-dashboard-design\node_modules\next\dist\compiled\webpack\bundle5.js:68468:17)
    at handleParseResult (C:\Users\lyndo\src\react-dashboard-design\react-dashboard-design\node_modules\next\dist\compiled\webpack\bundle5.js:68534:10)

**Comment by lyndonb1** [comment]
Running this from the command line and then build and npm run dev solved this

**Comment by lyndonb1** [comment]
Running this from the command line and then build and npm run dev solved this
